// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blmauyummcnxiwumbril.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbWF1eXVtbWNueGl3dW1icmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDk2ODIsImV4cCI6MjA3MDc4NTY4Mn0._wv-ddCw8A53L-X_AficPdHrC26a1r3ZsZAc777MBOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});